### ISSUE TITLE
📦: Failed Linux Compilation

### ISSUE THREAD

**Issue by tissatussa** [TheBlackPlague/StockDory#16]
lately i have trouble compiling some projects with Clang .. i mean in general, not only StockDory .. while searching for answers i find more people having the same problem, however, i wasn't able to solve it yet.

your README states one Requirement is `Clang (LLVM) >= 16.0.0` but on my current Xubuntu 22.04 i have 15.0.7 .. installing a newer Clang version seems rather tricky, i found https://releases.llvm.org and their GitHub page https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.0 but i'm hesitant to install such newest version by hand .. does your engine really need a newest Clang to compile ?

**Comment by TheBlackPlague** [comment]
Hello @tissatussa 

Yes, latest Clang is required. StockDory requires Clang >= 16.0.0 and a C++23 compatible header library. 

I can provide clang-16 installation instructions if needed.

**Comment by TheBlackPlague** [comment]
Hello @tissatussa 

I haven't heard back from you in quite a bit. I hope you respond by the end of this week. Otherwise, it'll only make sense to close this issue.

**Comment by tissatussa** [comment]
you offered me to give installation instructions, but i think i already found those, see the links i gave ..

> but i'm hesitant to install such newest version by hand

**Comment by tissatussa** [comment]
you may give your installation details, you can also close this Issue, the cause is clear now.

**Comment by TheBlackPlague** [comment]
Hello, 

On Windows and MacOS, you can use Chocolatey and Brew, respectively, to install the latest LLVM, CMake, and Ninja. 

On Linux, depending on your Distro, your package manager may be different, so you'll have to figure out how to install the latest required versions. On Ubuntu 22.04, this works for me:
```bash
wget https://apt.llvm.org/llvm.sh && \
sudo chmod +x llvm.sh && \
sudo ./llvm.sh 16 && \
sudo rm -rf llvm.sh
```

Having provided you with the necessary details and with your affirmative response, I will now close this issue. Best of luck.

**Comment by tissatussa** [comment]
i had several clang(++) versions installed, but i couldn't install v16 .. however, your method works on Xubuntu 22.04 : it adds a PPA, and after that i could install clang-16 by Synaptic (the regular way) .. to make the compilation work i only had to change 'clang' to 'clang-16' in your 'Setup Build Process' code line .. then compilation went well and i have a valid binary v1.0 with size 1.1 Mb !

**Comment by TheBlackPlague** [comment]
> i had several clang(++) versions installed, but i couldn't install v16 .. however, your method works on Xubuntu 22.04 : it adds a PPA, and after that i could install clang-16 by Synaptic (the regular way) .. to make the compilation work i only had to change 'clang' to 'clang-16' in your 'Setup Build Process' code line .. then compilation went well and i have a valid binary v1.0 with size 1.1 Mb !

Hello,

I'm glad to hear this solution worked for you. The size seems a bit extra, but I imagine native builds on different platforms lead to different binary sizes, which isn't totally unexpected. The best thing to do after the build on your platform is to run the `bench` command: `./StockDory bench`

As of [the latest commit](https://github.com/TheBlackPlague/StockDory/commit/9c44b89a156aafd70c1f525f01aebfa914d3b680), the command should output a node count of: `7489006`, and a reasonable speed (in NPS). Hard to say what reasonable is until I know more about your CPU.

If everything goes as expected, best of luck with using StockDory.

**Comment by tissatussa** [comment]
indeed : 7489006 nodes 1508359 nps
