### ISSUE TITLE
Is this based on Stockfish?

### ISSUE THREAD

**Issue by goteana** [TheBlackPlague/StockDory#20]
Is this based on Stockfish? What's the improvements?

**Comment by TheBlackPlague** [comment]
Hello @goteana,

I'm glad you're interested in the StockDory project. Unfortunately, this isn't really an issue, so I'll have to close this with this response.

However, to answer your question, StockDory isn't based on Stockfish. It's an independent, original engine, and the desire to work on it was inspired by the success and versatility of Stockfish and the Stockfish Team. Stockfish has greatly changed the chess engine world, and without it inspiring so much open-source progress, StockDory might've not existed today. The name serves as a token of gratitude to the Stockfish project. 

I wish you the best and thank you for your interest in the project.
