### ISSUE TITLE
Please add ARMv9.2, SVE2, Dot Product and Neon support

### ISSUE THREAD

**Issue by Chess321** [TheBlackPlague/StockDory#39]
It's sad that it's not possible to compile the newest version on Android and Linux devices.

**Comment by TheBlackPlague** [comment]
Hello,

What exact error are you encountering during compilation? @Chess321

**Comment by TheBlackPlague** [comment]
Hello,

As this issue hasn't been clarified for over 2 months, I assume it has been resolved.
